Sitegeist:
  Bitzer:
    constraintCheckPlugins:
      'Sitegeist\Bitzer\Review\Domain\Task\Review\ReviewTask':
        'Sitegeist\Bitzer\Review\Domain\Task\Review\ReviewTaskConstraintCheckPlugin': true
